version: "3.4"
services:
    nginx:
        build: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on: 
            - web
            - articles
            - books
    books:
        build: 
            context: books
            target: development
        volumes:
            - ./books/:/server/
        ports:
            - 3001:3000
    articles:
        build: 
            context: articles
            target: development
        volumes:
            - ./articles/:/server/
        ports:
            - 3002:3000
    web:
        build: 
            context: web
            target: development
        volumes:
            - ./web/:/server/
        ports:
            - 3000:3000
        depends_on: 
            - books
            - articles
    
            