version: "3"
services:
    nginx:
        build: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on: 
            - web
            - articles
            - books
    books:
        build: books
        command: npm run dev
        volumes:
            - ./books/:/server/
        ports:
            - 3001:3000
    articles:
        build: articles
        command: npm run dev
        volumes:
            - ./articles/:/server/
        ports:
            - 3002:3000
    web:
        build: web
        command: npm run dev
        volumes:
            - ./web/:/server/
        ports:
            - 3000:3000
        depends_on: 
            - books
            - articles
    
            